#ifndef PLANEGEOMETRY_GLOBAL_H
#define PLANEGEOMETRY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLANEGEOMETRY_LIBRARY)
#define PLANEGEOMETRY_EXPORT Q_DECL_EXPORT
#else
#define PLANEGEOMETRY_EXPORT Q_DECL_IMPORT
#endif

#endif // PLANEGEOMETRY_GLOBAL_H
